call npm install gulp
call npm install less
call npm install gulp-concat
call npm install gulp-uglify
call npm install gulp-sourcemaps
call npm install del
call npm install gulp-rename
call npm install gulp-util
call npm install vinyl-source-stream
call npm install vinyl-transform
call npm install stream
call npm install gulp-streamify
call npm install gulp-footer
call npm install os
call npm install reactify
call npm install browser-sync
call npm install lodash
call npm install exorcist
call npm install vinyl-buffer
call npm install gulp-if
call npm install gulp-watchify
call npm install reflux
call npm install react